-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 6343700aa063fe30acc319d2dc84353a35a3d6d0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501', '-v']
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: bcb1283267c0a041c77150a80a58f1bc2a3252d6
    hooks:
    -   id: validate_config
    -   id: validate_manifest
