language: python
env: # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=pypy
install: pip install tox --use-mirrors
script: tox


# Special snowflake.  Our tests depend on making real commits.
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
