language: python
dist: trusty
sudo: required
services:
    - docker
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py27 LATEST_GIT=1
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy2.7-5.10.0
        -   env: TOXENV=py37
            python: 3.7
            sudo: required
            dist: xenial
install: pip install coveralls tox
script: tox
before_install:
    - git --version
    - |
        if [ "$LATEST_GIT" = "1" ]; then
            testing/latest-git.sh
            export PATH="/tmp/git/bin:$PATH"
        fi
    - git --version
    - 'testing/get-swift.sh && export PATH="/tmp/swift/usr/bin:$PATH"'
    - 'curl -sSf https://sh.rustup.rs | bash -s -- -y'
    - export PATH="$HOME/.cargo/bin:$PATH"
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
        - $HOME/.rustup
        - $HOME/.swift
