environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py35

install:
    - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade
    - "mkdir -p C:\\Temp"
    - "SET TMPDIR=C:\\Temp"

# Not a C# project
build: false

before_test:
  - git config --global user.name "AppVeyor CI"
  - git config --global user.email "user@example.com"

test_script: tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.pre-commit'
