trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.14

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27, py37]
    os: windows
    additional_variables:
      COVERAGE_IGNORE_WINDOWS: '# pragma: windows no cover'
      TOX_TESTENV_PASSENV: COVERAGE_IGNORE_WINDOWS RUSTUP_HOME
      TEMP: C:\Temp  # remove when dropping python2
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: linux
    name_postfix: _latest_git
    pre_test:
    - task: UseRubyVersion@0
    - template: step--git-install.yml
    - template: step--rust-install.yml
    - bash: |
        testing/get-swift.sh
        echo '##vso[task.prependpath]/tmp/swift/usr/bin'
      displayName: install swift
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37]
    os: linux
    pre_test:
    - task: UseRubyVersion@0
    - template: step--rust-install.yml
    - bash: |
        testing/get-swift.sh
        echo '##vso[task.prependpath]/tmp/swift/usr/bin'
      displayName: install swift
