trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v1.0.0

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: windows
    pre_test:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
    - powershell: |
        Write-Host "##vso[task.prependpath]C:\Strawberry\perl\bin"
        Write-Host "##vso[task.prependpath]C:\Strawberry\perl\site\bin"
        Write-Host "##vso[task.prependpath]C:\Strawberry\c\bin"
      displayName: Add strawberry perl to PATH
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: linux
    name_postfix: _latest_git
    pre_test:
    - task: UseRubyVersion@0
    - template: step--git-install.yml
    - bash: |
        testing/get-swift.sh
        echo '##vso[task.prependpath]/tmp/swift/usr/bin'
      displayName: install swift
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy3, py36, py37, py38]
    os: linux
    pre_test:
    - task: UseRubyVersion@0
    - bash: |
        testing/get-swift.sh
        echo '##vso[task.prependpath]/tmp/swift/usr/bin'
      displayName: install swift
